[build-system]
requires = ["setuptools>=61", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

[project]
name = "climateclaw-client"
dynamic = ["version"]
description = "ClimateClaw Client library for connecting and interacting with an instance of the ClimateClaw chatbot."

readme = "README.md"
authors = [
    { name = 'Felix Oertel', email = 'oertel@dkrz.de' },
]
maintainers = [
    { name = 'Felix Oertel', email = 'oertel@dkrz.de' },
]
license = "EUPL-1.2"
license-files = ["LICENSE"]

classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]

requires-python = '>= 3.10'
dependencies = [
    # add your dependencies here
    "httpx",
    "pydantic",
    "py_oidc_auth_client>=2609.0.0",
    "nest_asyncio",
    "pillow",
]

[project.urls]
Homepage = "https://github.com/freva-org/climateclaw-client"

Documentation = "https://climate-claw-client.readthedocs.io/en/latest/"

Source = "https://github.com/freva-org/climateclaw-client"
Tracker = "https://github.com/freva-org/climateclaw-client/issues"


[project.optional-dependencies]
testsite = [
    "tox",
    "isort",
    "black",
    "blackdoc",
    "flake8",
    "pre-commit",
    "mypy",
    "pytest",
    "pytest-mock",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-httpx",
    "setuptools",
]
docs = [
    "sphinx>=7.0",
    "pydata-sphinx-theme>=0.7",
    "sphinx-autodoc2>=0.5.0",
    "autodocsumm>=0.2.12",
    "myst-parser>=2.0",
]
dev = [
    "climateclaw_client[testsite]",
    "climateclaw_client[docs]",
]

[tool.mypy]
ignore_missing_imports = true
exclude = "docs/*"
plugins = ['pydantic.mypy'] # type: ignore[misc]

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-data]
climateclaw_client = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
exclude = [
    'docs',
    'tests*',
]

[tool.pytest.ini_options]
addopts = '-v'
pythonpath = [
  ".", "src"
]

[tool.versioneer]
VCS = 'git'
style = 'pep440'
versionfile_source = 'src/climateclaw_client/_version.py'
versionfile_build = 'climateclaw_client/_version.py'
tag_prefix = ''
parentdir_prefix = "climateclaw_client-"

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src/climateclaw_client"]
float_to_top = true
known_first_party = "climateclaw_client"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.coverage.run]
omit = ["src/climateclaw_client/_version.py", "tests/*"]
